name: Daily Sync

on:
  schedule:
    # Run daily at 06:00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  daily-sync:
    runs-on: ubuntu-latest
    name: Sync Last 3 + Next 7 Days

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./FINAL_TOOLS_OUTPUT
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Sync
        working-directory: ./FINAL_TOOLS_OUTPUT
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: python daily_sync.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: daily-sync-logs
          path: ./FINAL_TOOLS_OUTPUT/automation.log
          retention-days: 7

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Daily sync failed. Check workflow logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })
